#!/bin/bash
pwd
echo "#####################"
ls -al
echo "#####################"
cd /app
./proxy http -t wss -p "0.0.0.0:443" –parent-ws-method="chacha20-ietf-poly1305" –parent-ws-password="6e2fda4a-37d9-4cc6-a0af-95272ee19319"
